--- pyproject.toml.orig	2026-04-18 13:52:13 UTC
+++ pyproject.toml
@@ -6,7 +6,7 @@ authors = [
 authors = [
     { name = "Gregory Szorc", email = "gregory.szorc@gmail.com" },
 ]
-license = "BSD-3-Clause"
+license = {text = "BSD-3-Clause"}
 requires-python = ">=3.9"
 classifiers = [
     "Development Status :: 5 - Production/Stable",
